angular.module('cbs')
.config(['$routeProvider',function($routeProvider){
    $routeProvider
    .when('/profile-listing',{
        templateUrl:'views/CBS/Views/iCreateProfileView',
        controller:'createProfile.controller'
    })
    .when('/profile-master',{
        templateUrl:'views/CBS/masterView',
        controller:'createProfile.controller'
    })
}]);